sudo: required

language: node_js
node_js:
  - '9.3'

# Branch Whitelist
branches:
    only:
        - master
        - develop

script:
  # Run linting and tests
  - npm run verify

  # Build your site (e.g., HTML, CSS, JS) here.
  - ng build --prod --base-href ""

deploy:
  # Control deployment by setting a value for `on`. Setting the `branch`
  # option to `master` means Travis will only attempt a deployment on
  # builds of your repo's master branch (e.g., after you merge a PR).
  on:
    branch: master

  # Ensure that Travis know to deploy to S3.
  provider: s3

  # You can refer to environment variables from Travis repo settings!
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY

  # Name of the S3 bucket to which your site should be uploaded.
  bucket: ians-personal-website

  # Prevent Travis from deleting your built site so it can be uploaded.
  skip_cleanup: true

  # Path to a directory containing your built site.
  local_dir: dist

  # Set the Cache-Control header.
  cache_control: "max-age=21600"